<?php
/**
 * TL_ROOT/system/modules/newsitemwalker/languages/de/default.php 
 * 
 * Contao extension: newsitemwalker 2.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   :  
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['nextArticle']['0'] = "nächster Artikel";
$GLOBALS['TL_LANG']['MSC']['nextArticle']['1'] = "gehe zum nächsten Artikel";
$GLOBALS['TL_LANG']['MSC']['prevArticle']['0'] = "älterer Artikel";
$GLOBALS['TL_LANG']['MSC']['prevArticle']['1'] = "gehe zum nächst älteren Artikel";

