<?php
/**
 * TL_ROOT/system/modules/newsitemwalker/languages/de/modules.php 
 * 
 * Contao extension: newsitemwalker 2.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   :  
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['newsitemwalker']['0'] = "News-Item-Walker";
$GLOBALS['TL_LANG']['FMD']['newsitemwalker']['1'] = "Generiert zwei Links. Wenn das newsitemwalker-Modul oberhalb eines newsreader-Moduls, platziert wird, kann ganz einfach zwischen den einzelnen News-Artikeln hin und her navigiert werden.";
 
?>
