<?php
/**
 * TL_ROOT/system/modules/newsitemwalker/languages/de/tl_module.php 
 * 
 * Contao extension: newsitemwalker 2.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   :  
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['newsItemWalkerTpl']['0'] = "Template";
$GLOBALS['TL_LANG']['tl_module']['newsItemWalkerTpl']['1'] = "Hier können Sie das Template auswählen.";
$GLOBALS['TL_LANG']['tl_module']['news_archives']['0'] = "Nachrichtenarchive wählen";
$GLOBALS['TL_LANG']['tl_module']['news_archives']['1'] = "Wählen Sie die Nachrichtenarchive aus, die berücksichtigt werden sollen.";
$GLOBALS['TL_LANG']['tl_module']['template_legend'] = "Template-Einstellungen";
 
?>
